default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5

development:
  <<: *default
  database: message_db
  username: pguser
  password: postgres

test:
  <<: *default
  database: myapp_test